
import AuthProvider from "@/components/AuthProvider";
import NavBar from "@/components/NavBar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react"
import {AppWrapper} from './context/ContextProvider'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Momentum 2024",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <AppWrapper>
            <NavBar/>
            {children}
          </AppWrapper>
        </AuthProvider>
        <Analytics/>
      </body>
    </html>
  );
}
